version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "NORSI-TRANS"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "12345678"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db:
    driver: local